### ISSUE TITLE
Watching for create/rename .hbs files with HMR is not fully working

### ISSUE THREAD

**Issue by 5ulo** [webdiscus/html-bundler-webpack-plugin#13]
## Current behaviour

I have suspicion that there's something wrong with files watching (HMR module) or something similiar. Imagine this situation:

You run `npm run start` to watch files for changes (HMR enabled), then include existing partial `{{>foo}}`, then create a new partial called `bar.hbs` and include it inside index file as follows `{{>bar}}`. You will get an error:
```
ERROR in ./src/views/pages/index.hbs
Module Error (from ./node_modules/html-bundler-webpack-plugin/src/Loader/index.js):

 html-bundler-webpack-plugin  Preprocessor failed.
File: src/views/pages/index.hbs
Error: The partial bar could not be found
    at Object.invokePartial (/Users/e/http/devel/test-bundler/node_modules/handlebars/dist/cjs/handlebars/runtime.js:332:11)
    at Object.invokePartialWrapper [as invokePartial] (/Users/e/http/devel/test-bundler/node_modules/handlebars/dist/cjs/handlebars/runtime.js:84:39)
    at Object.eval [as main] (eval at createFunctionContext (/Users/e/http/devel/test-bundler/node_modules/handlebars/dist/cjs/handlebars/compiler/javascript-compiler.js:262:23), <anonymous>:16:28)
    at main (/Users/e/http/devel/test-bundler/node_modules/handlebars/dist/cjs/handlebars/runtime.js:208:32)
    at ret (/Users/e/http/devel/test-bundler/node_modules/handlebars/dist/cjs/handlebars/runtime.js:212:12)
    at ret (/Users/e/http/devel/test-bundler/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:519:21)
    at render (/Users/e/http/devel/test-bundler/node_modules/html-bundler-webpack-plugin/src/Loader/Preprocessors/Handlebars/index.js:102:93)
    at Promise.then.errorStage (/Users/e/http/devel/test-bundler/node_modules/html-bundler-webpack-plugin/src/Loader/index.js:54:16)
    at new Promise (<anonymous>)
    at Object.loader (/Users/e/http/devel/test-bundler/node_modules/html-bundler-webpack-plugin/src/Loader/index.js:43:3)
```
So you have to stop the npm and run `npm run start` again.. then the new `bar.hbs` is recognised. Now let's say you need to rename the `bar.hbs` to `lorem.hbs` because of for whatever reason. So you change `{{>bar}}` to `{{>lorem}}` in index file, get an error (which was expected as the file `lorem.hbs` does not yet exist), then you rename `bar.hbs` to `lorem.hbs` and you get a huuuge red error in terminal:
```
webpack 5.84.1 compiled with 1 error in 32 ms
<e> [webpack-dev-middleware] Error: ENOENT: no such file or directory, open '/Users/e/http/devel/test-bundler/src/views/partials/bar.hbs'
<e>     at Object.openSync (node:fs:585:3)
<e>     at Object.readFileSync (node:fs:453:35)
<e>     at Object.updatePartials [as watch] (/Users/e/http/devel/test-bundler/node_modules/html-bundler-webpack-plugin/src/Loader/Preprocessors/Handlebars/index.js:19:27)
<e>     at Function.watchRun (/Users/e/http/devel/test-bundler/node_modules/html-bundler-webpack-plugin/src/Loader/Preprocessor.js:84:20)
<e>     at Function.watchRun (/Users/e/http/devel/test-bundler/node_modules/html-bundler-webpack-plugin/src/Plugin/PluginService.js:60:20)
<e>     at /Users/e/http/devel/test-bundler/node_modules/html-bundler-webpack-plugin/src/Plugin/AssetCompiler.js:166:21
<e>     at Hook.eval [as callAsync] (eval at create (/Users/e/http/devel/test-bundler/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
<e>     at run (/Users/e/http/devel/test-bundler/node_modules/webpack/lib/Watching.js:168:33)
<e>     at /Users/e/http/devel/test-bundler/node_modules/webpack/lib/Watching.js:155:6
<e>     at /Users/e/http/devel/test-bundler/node_modules/webpack/lib/HookWebpackError.js:68:3 {
<e>   errno: -2,
<e>   syscall: 'open',
<e>   code: 'ENOENT',
<e>   path: '/Users/e/http/devel/test-bundler/src/views/partials/bar.hbs'
<e> }
```
The same goes with pages (views).
But that's not all. Your partials are structured like this:
```
partials/
│- foo.hbs
│- bar.hbs
└─ blog/
  │- list.hbs
  └─ card.hbs
```
If you do some change inside `card.hbs` the page will be reloaded (so HMR is watchind) but no change will be visible. But if you update `foo|bar.hbs` file it will update also the `card.hbs` output.

## Expected behaviour

I expect the `.hbs` would be watched for changes. So if I create new `contact.hbs` view file I can access it as `/contact.html`. If I create new partial or sub-partial, would be great to have the option to immediately inlcude it `{{>blog/card}}` without stopping npm. And also the sub-parts should be watched. This expected behaviour is working for example with `HandlebarsPlugin`.

### Reproduction Example

1. Run `npm run start` with enabled HMR
2. inside index view include `{{>foo}}` partial.
3. in filesystem rename `foo.hbs` to `bar.hbs` -> error
4. create new partials `lorem.hbs` and include it in index `{{>lorem}}` -> error
5. create new page `contact.hbs` and load it `/contact.html` -> error `Cannot GET /contact`

## Environment

- OS: macOS 13.4
- version of Node.js: v18.16.0
- version of Webpack: 5.84.1
- version of the Plugin: 1.18.0

## Additional context

Here's my `webpack.config.js`:
```javascript
const path = require('path');
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');

module.exports = (env, argv) => {
    return {
        output: {
            path: path.join(process.cwd(), 'dist'),
        },
        devServer: {
            port: 3000,
            open: true,
            host: '0.0.0.0',
            static: {
                directory: path.join(__dirname, 'dist'),
            },
            watchFiles: {
                paths: ['src/**/*.*'],
                options: {
                    usePolling: true,
                },
            },
        },
        plugins: [
            new HtmlBundlerPlugin({
                entry: path.join(__dirname, 'src/views/pages'), // home, contact, blog...
                loaderOptions: {
                    data: path.join(process.cwd(), 'src/data.json'),
                    root: path.join(__dirname, 'src'),
                    preprocessor: 'handlebars',
                    preprocessorOptions: {
                        // root: path.join(__dirname, 'src/views/'),
                        views: [
                            'src/views/pages',
                        ],
                        partials: [
                            path.join(__dirname, 'src/views/partials'),
                        ],
                    },
                },
                js: {
                    filename: 'js/[name].[contenthash:8].js',
                },
                css: {
                    filename: 'css/[name].[contenthash:8].css',
                },
            }),
        ],
        module: {
            rules: [
                {
                    test: /\.(css|sass|scss)$/,
                    use: ['css-loader', 'sass-loader'],
                },
                {
                    test: /\.(ico|png|jp?g|svg)$/,
                    type: 'asset/resource',
                    generator: {
                        filename: 'img/[name].[hash:8][ext][query]',
                    },
                },
                {
                    test: /\.(html|hbs|handlebars)$/,
                    loader: HtmlBundlerPlugin.loader,
                }
            ],
        },
    }
};
```
And my dir structure:
```
.
├── dist
├── package-lock.json
├── package.json
├── src
│   ├── css
│   ├── data.json
│   ├── img
│   ├── js
│   └── views
│       ├── pages
│       │   ├── index.hbs
│       │   └── sub.hbs
│       └── partials
│           ├── foo.hbs
│           ├── lorem.hbs
│           └── blog
│               └── card.hbs
└── webpack.config.js
```

**Comment by webdiscus** [comment]
Hello @5ulo,

thanks for the issue report.
I research the problem and try to fix it.

### Note

**Comment by webdiscus** [comment]
Hello @5ulo,

in new release 2.0.1 following is fixed:

1. inside index.hbs include or remove {{>foo}} partial, works
2. create new partials lorem.hbs and include it in index {{>lorem}}, works
3. rename lorem.hbs to lorem2.hbs -> recoverable error partial lorem not found, it's OK) -> rename the partial in template to {{>lorem2}}  -> auto reload -> OK

Create new page or rename a entry template still not works. I don't know how to fix it. Currently this is impossible. It is Webpack specifically feature. I have research it and haven't found a solution, sorry.
For this case I have created separate issue: [How to watch entry directory for changes](https://github.com/webdiscus/html-bundler-webpack-plugin/issues/22).

**Comment by 5ulo** [comment]
Thanks @webdiscus . I checked the functionality and works as expected.

**Comment by webdiscus** [comment]
@5ulo 

new `v2.1.0` is released.
Now you can add/delete/rename a template file in the entry path without restarting Webpack.
