### ISSUE TITLE
Cannot read properties of null (reading 'isFileWatchable')

### ISSUE THREAD

**Issue by webdiscus** [webdiscus/html-bundler-webpack-plugin#132]
If run `webpack serve`, after changes in a SCSS file occurs the error:
```
/Build/node_modules/html-bundler-webpack-plugin/src/Plugin/AssetCompiler.js:603
const isFileWatchable = dependency.isFileWatchable(fileName);
^

TypeError: Cannot read properties of null (reading 'isFileWatchable')
at HtmlBundlerPlugin.invalidate (/Build/node_modules/html-bundler-webpack-plugin/src/Plugin/AssetCompiler.js:603:42)
at Hook.eval [as call] (eval at create (/Build/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:9:1)
at Hook.CALL_DELEGATE [as _call] (/Build/node_modules/tapable/lib/Hook.js:14:14)
at Watchpack.<anonymous> (/Build/node_modules/webpack/lib/Watching.js:390:35)
at Object.onceWrapper (node:events:633:26)
at Watchpack.emit (node:events:518:28)
at Watchpack._onChange (/Build/node_modules/watchpack/lib/watchpack.js:364:9)
at Watcher.<anonymous> (/Build/node_modules/watchpack/lib/watchpack.js:89:15)
at Watcher.emit (node:events:518:28)
at /Build/node_modules/watchpack/lib/DirectoryWatcher.js:220:41

Node.js v22.11.0
```

**Comment by webdiscus** [comment]
The issue is fixed in `v4.10.4`.
