### ISSUE TITLE
RSPack support and compatibility

### ISSUE THREAD

**Issue by KrzysztofZawisla** [webdiscus/html-bundler-webpack-plugin#55]
## Feature request

**What is motivation or use case for adding/changing the behavior?**
Would be nice to add compatibility with rspack ecosystem as many other webpack plugins are already compatible with rspack. In my project, it's the only plugin that is incompatible with rspack and doesn't have any other equivalent

Useful links: https://www.rspack.dev/

**Describe the solution you'd like**
Resolve the error on the attached screenshot

![rspack](https://github.com/webdiscus/html-bundler-webpack-plugin/assets/32432944/d06453d0-8ee1-40c3-b8ed-e0503245892f)

**Describe alternatives you've considered**
-

**Comment by exocornet** [comment]
Hello. I'm also trying to switch to RSPack and have the same problem with the plugin. I would like to see support in the near future. Essentially he is complaining about pug-plugin joining the RSPack ecosystem. Thank you.

**Comment by webdiscus** [comment]
@KrzysztofZawisla, @davidmurdoch, @exocornet 

Currently, RSPack `v0.5.6` is yet not 100% compatible with the Webpack.

Using the `html-bundler-webpack-plugin` with `RSPack` occurs the issue:

```
/Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/@rspack/core/dist/Compiler.js:518
    __classPrivateFieldSet(this, _Compiler_instance, new instanceBinding.Rspack(rawOptions, this.builtinPlugins, {
                                                     ^

Error: Failed to convert JavaScript value `function filenameFn(..) ` into rust type `String`

    at Compiler._Compiler_getInstance (/Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/@rspack/core/dist/Compiler.js:518:54)
    at Compiler.build (/Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/@rspack/core/dist/Compiler.js:384:87)
    at /Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/@rspack/core/dist/Watching.js:263:23
    at Hook.eval [as callAsync] (eval at create (/Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._Watching_go (/Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/@rspack/core/dist/Watching.js:253:34)
    at Watching._Watching_invalidate (/Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/@rspack/core/dist/Watching.js:217:74)
    at /Users/biodiscus/Devel/Projects/GitHub/webpack/html-bundler-webpack-plugin/experiments/rspack/node_modules/@rspack/core/dist/Watching.js:51:94
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'GenericFailure'
}
```

This is a BUG on the `RSPack` side.

Here is the minimal usage example [rspack-html-bundler](https://github.com/webdiscus/html-bundler-webpack-plugin/tree/master/experiments/rspack).


```js
const path = require('path');
const HtmlBundlerPlugin = require('html-bundler-webpack-plugin');

module.exports = {
  output: {
    path: path.join(__dirname, 'dist/'),
    publicPath: '',
  },

  entry: {},

  plugins: [
    // TODO: fix rspack issue
    new HtmlBundlerPlugin({
      entry: {
        index: './src/template.html',
      },
    }),
  ],
};
```

## How to reproduce

```
git clone https://github.com/webdiscus/html-bundler-webpack-plugin.git
cd html-bundler-webpack-plugin/experiments/rspack
npm i
npm run dev
```

Please, can you create an issue by the `RSPack` to add the compatibility with this plugin.

> 📌 **Note**
> A symbiosis of the fast RSPack and the powerful [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) could be a `Vite` killer.

**Comment by elseify** [comment]
Hello, Rspack 1.0 has been released! Can you try to add his support again?)

**Comment by webdiscus** [comment]
Hi @elseify,

Rspack 1.0 is not yet compatible with `core webpack features`.

Rspack implements "~10%" of the core (mandatory) features of Webpack, so it is not possible to make this powerful Webpack plugin compatible with Rspack. In fact, Rspack lacks important Webpack features.

I checked the new version and saw many missing features that the plugin uses.

-  RSPack doesn't implemet the `compilation` object as the instanceof of the `Compilation`
- missing `contextModuleFactory.hooks.alternativeRequests`
- missing `normalModuleFactory.hooks.createModuleClass`
- missing `normalModuleFactory.hooks.module`
- missong `compilation.hooks.renderManifest`
- ...

**Comment by elseify** [comment]
I understand, it's sad of course. Webpack has become too slow

**Comment by webdiscus** [comment]
> Webpack has become too slow

For using Webpack with React or Vue, yes, is too slow. But it is the problem of the React with a lot of components, not Webpack ;-)

Webpack is ideal to generate classic (old school) HTML pages, w/o modern monster frameworks.

For example, I have for my project over 50 templates (Pug, Handlebars, etc.) and to compile all pages with JS, SCSS, takes ca. 8-10 seconds (M1 Pro). In dev (watch/serve) mode recompilation after changes takes ca. 0.3-0.9 seconds. It's ok.

P.S. For React/Vue there is a very cool Vite.

P.S.S. can you please describe your project:
- how many pages
- whether is used a templating engine
- how many JS components or frameworks/libs
- how large is SCSS code base
- how long compiles your project
- how long compiles after changes (serve/watch)

**Comment by eungyeole** [comment]
@webdiscus any updates on the issue?

**Comment by webdiscus** [comment]
> @webdiscus any updates on the issue?

It is not the issue of this plugin. It is the `missing implementations` of core Webpack features in Rspack.

Webpack is best of the best bundler/compiler with rich functionality covered 100% of all possible requirements for web development. No Vite or Rspack or Turbo can do what Webpack can.

Yes, Webpack is much slower than Rspack, but Rspack has much less functionality.
I doubt that Rspack will ever reach the functionality of Webpack. 

> Until Rspack implements all the core features of Webpack, this plugin cannot be adapted to Rspack.

I'm sorry.
